// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD68n_s2MiwPfMVoCQmXBaBhLtSiCgGkbQ',
    appId: '1:230961232990:web:4fc2d4f03b3425761488cf',
    messagingSenderId: '230961232990',
    projectId: 'testing-cli-84e74',
    authDomain: 'testing-cli-84e74.firebaseapp.com',
    storageBucket: 'testing-cli-84e74.appspot.com',
    measurementId: 'G-5LS51KNX7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzbYdG4oA8pEU1eSofWW_mMNa1ZY_1xfQ',
    appId: '1:230961232990:android:ecb1626000ee37831488cf',
    messagingSenderId: '230961232990',
    projectId: 'testing-cli-84e74',
    storageBucket: 'testing-cli-84e74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88Zg83cGYoJGDCJXLQ9PKe8kaSES2o3A',
    appId: '1:230961232990:ios:0a7e1cd09b79382a1488cf',
    messagingSenderId: '230961232990',
    projectId: 'testing-cli-84e74',
    storageBucket: 'testing-cli-84e74.appspot.com',
    iosBundleId: 'com.example.me',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA88Zg83cGYoJGDCJXLQ9PKe8kaSES2o3A',
    appId: '1:230961232990:ios:0a7e1cd09b79382a1488cf',
    messagingSenderId: '230961232990',
    projectId: 'testing-cli-84e74',
    storageBucket: 'testing-cli-84e74.appspot.com',
    iosBundleId: 'com.example.me',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD68n_s2MiwPfMVoCQmXBaBhLtSiCgGkbQ',
    appId: '1:230961232990:web:bcebc418c5121e9b1488cf',
    messagingSenderId: '230961232990',
    projectId: 'testing-cli-84e74',
    authDomain: 'testing-cli-84e74.firebaseapp.com',
    storageBucket: 'testing-cli-84e74.appspot.com',
    measurementId: 'G-0GQMEDS0KF',
  );
}
